service: pollencount

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  profile: ${file(env.yml):profile}
  stage: ${file(env.yml):stage}

functions:
  alexa:
    handler: handler.handler
    events:
      - alexaSkill
